[project]
name = "structural-extanalyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-community>=0.4.2",
    "pdfplumber>=0.11.10",
    "pymupdf>=1.28.2",
    "pypdf>=6.15.0",
]

[tool.uv.workspace]
members = []

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
